version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    container_name: ruby_postgres_c
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp_development
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - web_volume:/image-gallery-app
    ports:
      - 3000:3000
    depends_on:
      - db
    container_name: ruby_web_c
volumes:
  web_volume:
  postgres_volume:

