version: "3.9"
services:
  db:
    image: postgres:14
    container_name: postgres_c
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  back-end:
    platform: linux/amd64
    build: ./back-end/api
    container_name: back-end_c
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./back-end:/app
    environment:
      - DATASOURCE=jdbc:postgresql://db:5432/demo
  front-end:
    build: ./front-end
    container_name: front-end_c
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app
    environment:
      - REACT_APP_USER_NAME=Docker
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
volumes:
  postgres_volume:
